app:
  jwt:
    jwt-secret-key: wafflestudio
    jwt-expiration-in-ms: 10800000

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/seminar?serverTimezone=UTC
    username: waffle-spring
    password: wafflestudio
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      # create: 시작 시 테이블 drop 후 재생성
      # update: 시작 시 자동 migrate
      # none: db 그대로
      # create-drop: 시작 시 테이블 create, 종료 시 drop
#    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://spring-seminar-database.czf0lti4mvdi.us-east-2.rds.amazonaws.com/seminar?serverTimezone=UTC
    username: admin
    password: Alzhs21686!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
