name: Deploy

on:
  pull_request:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:    
    - name: Create application
      run: ehco "${{ secrets.APPLICATION_YAML }}" > ./seminar1/assignment1/seminar/src/main/resources/application.yml
