# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:    
      - name: Create yaml
        run: ehco "${{ secrets.APPLICATION_YAML }}" > ./seminar1/assignment1/seminar/src/main/resources/application.yml
